on: 
  pull_request: 
    types: [opened, edited, reopened, ready_for_review]


jobs:
  check-signer:
    runs-on: ubuntu-latest
    name: Check membership status
    steps:
      - uses: julien51/token-gated-commit-action@v1.1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
