on: 
  pull_request: 
    types: [opened, edited, reopened, ready_for_review]


jobs:
  check-signer:
    runs-on: ubuntu-latest
    name: Check membership status
    steps:
      - uses: julien51/token-gated-commit-action@v1.1
        with:
          locks: '[{"address": "0x0759070d28F788947a99828b1226b930C970027F", "network": 4}, {"address": "0x1206b31eEd5Ceb34E91f53249339Ae221e673177", "network": 4}]'
