on: 
  pull_request:

jobs:
  check-signer:
    runs-on: ubuntu-latest
    name: Check membership status
    steps:
      - uses: julien51/token-gated-commit-action@v1.1
        with:
          locks: '[{"address": "0x123", "network": 4}, {"address": "0x567", "network": 1}]'